// This file is intended to be generated by the Supabase CLI:
//  supabase gen types typescript --schema public > src/types/database.ts
// If you don't have the CLI installed yet, install it and run the above command.

// Minimal hand-maintained types for local development fallbacks.
export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export type Database = {
  public: {
    Tables: {
      farm_cycle: {
        Row: {
          id: number
          name: string
          start_date: string
          end_date: string | null
          created_at: string
        }
      }
      // ... other table types can be generated by the CLI
    }
  }
}

export type FarmCycleRow = Database['public']['Tables']['farm_cycle']['Row']


